"use server";

import {revalidatePath} from "next/cache";import {createAdminClient} from "@/lib/supabase/admin";import {requireAdmin} from "@/lib/admin/auth";import {requestAuditContext,writeAudit} from "@/lib/admin/audit";
const text=(form:FormData,key:string)=>String(form.get(key)??"").trim();
async function mutate(actor:string,entity:string,id:string|null,values:Record<string,unknown>){const request=await requestAuditContext();const{data,error}=await createAdminClient().rpc("admin_mutate_entity",{p_actor_user_id:actor,p_entity:entity,p_id:id,p_values:values,...request});if(error)throw new Error(error.message);if(!data?.ok)throw new Error(data?.code??"Operación denegada");return data;}

export async function generateInviteLink(form:FormData){const context=await requireAdmin();const email=text(form,"email").toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email))throw new Error("Correo inválido");const{data,error}=await createAdminClient().auth.admin.generateLink({type:"invite",email});await writeAudit({actorUserId:context.userId,action:"user.invite.generate",resourceType:"user",result:error?"failure":"success",after:{emailDomain:email.split("@")[1]}});if(error)throw new Error(error.message);return{link:data.properties.action_link}}
export async function updateUserAccess(form:FormData){const context=await requireAdmin();const request=await requestAuditContext();const{error}=await createAdminClient().rpc("set_user_access",{p_actor_user_id:context.userId,p_target_user_id:text(form,"userId"),p_suspended:text(form,"suspended")==="true",p_reason:text(form,"reason"),...request});if(error)throw new Error(error.message);revalidatePath("/admin/users")}
export async function updateUserRole(form:FormData){const context=await requireAdmin(true);const request=await requestAuditContext();const{error}=await createAdminClient().rpc("set_user_role",{p_actor_user_id:context.userId,p_target_user_id:text(form,"userId"),p_role:text(form,"role"),...request});if(error)throw new Error(error.message);revalidatePath("/admin/users")}
export async function revokeUserSessions(form:FormData){const context=await requireAdmin();const request=await requestAuditContext();const{error}=await createAdminClient().rpc("revoke_user_sessions",{p_actor_user_id:context.userId,p_target_user_id:text(form,"userId"),...request});if(error)throw new Error(error.message);revalidatePath("/admin/users")}
export async function updateProfile(form:FormData){const context=await requireAdmin();await mutate(context.userId,"profile",text(form,"userId"),{display_name:text(form,"displayName"),locale:text(form,"locale"),timezone:text(form,"timezone")||"America/Montevideo"});revalidatePath("/admin/users")}
export async function updateRequest(form:FormData){const context=await requireAdmin();await mutate(context.userId,"access_request",text(form,"id"),{status:text(form,"status"),resolution_note:text(form,"resolutionNote")});revalidatePath("/admin/requests")}
export async function savePlanEntitlement(form:FormData){const context=await requireAdmin();let value:unknown;try{value=JSON.parse(text(form,"value"))}catch{throw new Error("El valor debe ser JSON válido")}await mutate(context.userId,"plan_entitlement",text(form,"planId"),{capability:text(form,"capability"),value});revalidatePath("/admin/plans")}
export async function saveSubscription(form:FormData){const context=await requireAdmin();const request=await requestAuditContext();const values={user_id:text(form,"userId"),plan_id:text(form,"planId"),status:text(form,"status"),provider:text(form,"provider")||"manual",provider_subscription_id:text(form,"providerReference"),purchaser_email:text(form,"purchaserEmail"),starts_at:text(form,"startsAt"),current_period_ends_at:text(form,"endsAt")};const{error}=await createAdminClient().rpc("record_subscription_change",{p_actor_user_id:context.userId,p_subscription_id:text(form,"id")||null,p_values:values,...request});if(error)throw new Error(error.message);revalidatePath("/admin/plans")}
export async function grantPremiumTrials(form:FormData){const context=await requireAdmin();const request=await requestAuditContext();const{error}=await createAdminClient().rpc("grant_premium_trials",{p_actor_user_id:context.userId,p_user_id:text(form,"userId"),p_task_id:text(form,"taskId"),p_quantity:Number(text(form,"quantity")),p_reason:text(form,"reason"),...request});if(error)throw new Error(error.message);revalidatePath("/admin/plans")}
export async function saveUserEntitlement(form:FormData){const context=await requireAdmin();let value:unknown;try{value=JSON.parse(text(form,"value"))}catch{throw new Error("JSON inválido")}await mutate(context.userId,"user_entitlement",null,{user_id:text(form,"userId"),capability:text(form,"capability"),value,reason:text(form,"reason"),expires_at:text(form,"expiresAt")});revalidatePath("/admin/plans")}
export async function savePlan(form:FormData){const context=await requireAdmin();await mutate(context.userId,"plan",text(form,"id")||null,{code:text(form,"code"),name:text(form,"name"),description:text(form,"description"),is_active:text(form,"isActive")!=="false"});revalidatePath("/admin/plans")}
export async function saveTask(form:FormData){const context=await requireAdmin();await mutate(context.userId,"task",text(form,"id"),{is_active:text(form,"isActive")==="true",is_premium:text(form,"isPremium")==="true",sort_order:Number(text(form,"sortOrder"))||0});revalidatePath("/admin/catalog");revalidatePath("/prompts")}
export async function saveTaskTranslation(form:FormData){const context=await requireAdmin();await mutate(context.userId,"task_translation",text(form,"taskId"),{locale:text(form,"locale"),name:text(form,"name"),description:text(form,"description"),user_prompt_template:text(form,"promptTemplate"),system_prompt:text(form,"systemPrompt")});revalidatePath("/admin/catalog");revalidatePath("/prompts")}
export async function saveCategory(form:FormData){const context=await requireAdmin();await mutate(context.userId,"category",text(form,"id")||null,{code:text(form,"code"),sort_order:Number(text(form,"sortOrder"))||0,is_active:text(form,"isActive")!=="false"});revalidatePath("/admin/catalog");revalidatePath("/prompts")}
export async function createTask(form:FormData){const context=await requireAdmin();const request=await requestAuditContext();const{error}=await createAdminClient().rpc("admin_create_task",{p_actor_user_id:context.userId,p_code:text(form,"code"),p_category_id:text(form,"categoryId"),p_sort_order:Number(text(form,"sortOrder"))||0,...request});if(error)throw new Error(error.message);revalidatePath("/admin/catalog")}
export async function saveCategoryTranslation(form:FormData){const context=await requireAdmin();const request=await requestAuditContext();const{error}=await createAdminClient().rpc("admin_save_category_translation",{p_actor_user_id:context.userId,p_category_id:text(form,"categoryId"),p_locale:text(form,"locale"),p_name:text(form,"name"),p_description:text(form,"description"),...request});if(error)throw new Error(error.message);revalidatePath("/admin/catalog");revalidatePath("/prompts")}
export async function saveProvider(form:FormData){const context=await requireAdmin();await mutate(context.userId,"provider",text(form,"id")||null,{code:text(form,"code"),name:text(form,"name"),is_active:text(form,"isActive")!=="false"});revalidatePath("/admin/models")}
export async function saveModel(form:FormData){const context=await requireAdmin();await mutate(context.userId,"model",text(form,"id")||null,{provider_id:text(form,"providerId"),code:text(form,"code"),display_name:text(form,"displayName"),is_active:text(form,"isActive")!=="false"});revalidatePath("/admin/models")}
export async function saveModelRoute(form:FormData){const context=await requireAdmin();const request=await requestAuditContext();const{error}=await createAdminClient().rpc("update_model_route",{p_actor_user_id:context.userId,p_rule_id:text(form,"id"),p_active:text(form,"isActive")==="true",p_priority:Number(text(form,"priority"))||0,...request});if(error)throw new Error(error.message);revalidatePath("/admin/models")}
export async function saveSetting(form:FormData){const context=await requireAdmin(true);let value:unknown;try{value=JSON.parse(text(form,"value"))}catch{throw new Error("JSON inválido")}const request=await requestAuditContext();const{error}=await createAdminClient().rpc("update_operational_setting",{p_actor_user_id:context.userId,p_key:text(form,"key"),p_value:value,...request});if(error)throw new Error(error.message);revalidatePath("/admin/settings")}
export async function deleteUserPermanently(form:FormData){const context=await requireAdmin(true);const targetId=text(form,"userId"),confirmation=text(form,"confirmation"),password=text(form,"password");if(!password||targetId===context.userId)throw new Error("Operación no permitida");const admin=createAdminClient();const[{data:actor},{data:target}]=await Promise.all([admin.auth.admin.getUserById(context.userId),admin.auth.admin.getUserById(targetId)]);if(!actor.user?.email||!target.user?.email||confirmation.toLowerCase()!==target.user.email.toLowerCase())throw new Error("La confirmación no coincide");const sessionClient=await import("@/lib/supabase/server").then(module=>module.createClient());const{error:authError}=await sessionClient.auth.signInWithPassword({email:actor.user.email,password});if(authError){await writeAudit({actorUserId:context.userId,action:"user.delete",resourceType:"user",result:"denied"});throw new Error("Reautenticación fallida")}const request=await requestAuditContext();const{data:files}=await admin.from("attachments").select("storage_bucket,storage_path").eq("user_id",targetId);const prepared=await admin.rpc("prepare_user_deletion",{p_actor_user_id:context.userId,p_target_user_id:targetId,...request});if(prepared.error)throw new Error(prepared.error.message);const operationId=prepared.data;const{error}=await admin.auth.admin.deleteUser(targetId);if(error){await admin.rpc("fail_user_deletion",{p_actor_user_id:context.userId,p_operation_id:operationId});throw new Error(error.message)}for(const bucket of new Set((files??[]).map(file=>file.storage_bucket))){const paths=(files??[]).filter(file=>file.storage_bucket===bucket).map(file=>file.storage_path);if(paths.length)await admin.storage.from(bucket).remove(paths)}const finalized=await admin.rpc("finalize_user_deletion",{p_actor_user_id:context.userId,p_operation_id:operationId});if(finalized.error)throw new Error(finalized.error.message);revalidatePath("/admin/users");revalidatePath("/admin/settings")}
export async function logConversationRead(conversationId:string){const context=await requireAdmin(true);await writeAudit({actorUserId:context.userId,action:"conversation.read",resourceType:"conversation",resourceId:conversationId})}
