import Link from "next/link";import{getDashboard}from"@/lib/admin/data";import{requireAdmin}from"@/lib/admin/auth";import{PageHeader,Card,field}from"./ui";
export default async function AdminDashboard({searchParams}:{searchParams:Promise<{days?:string;start?:string;end?:string}>}){
 const context=await requireAdmin(),params=await searchParams,requested=Number(params.days??30),days=[7,30,90].includes(requested)?requested:30,data=await getDashboard(context,days,params.start,params.end);
 const modelStats=Object.entries(data.attempts.reduce<Record<string,{total:number;failed:number}>>((all,item)=>{const key=`${item.provider_code}/${item.model_code}`;all[key]??={total:0,failed:0};all[key].total++;if(item.status==="failed")all[key].failed++;return all},{}));
 return <><PageHeader title="Dashboard operativo" description="Métricas de producto e inferencia, sin contenido de conversaciones."/><form className="mb-5 flex flex-wrap items-center gap-2"><select name="days" defaultValue={days} className={field}><option value="7">7 días</option><option value="30">30 días</option><option value="90">90 días</option></select><input type="date" aria-label="Desde" name="start" defaultValue={params.start} className={field}/><input type="date" aria-label="Hasta" name="end" defaultValue={params.end} className={field}/><button className="font-bold text-[#1261ff]">Aplicar</button></form>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card label="Usuarios" value={data.users}/><Card label="Usuarios activos" value={data.activeUsers}/><Card label="Ejecuciones" value={data.executions}/><Card label="Usos" value={data.uses}/><Card label="Tasa de fallo" value={`${(data.failureRate*100).toFixed(1)}%`}/><Card label="Latencia media" value={`${data.averageLatency} ms`}/><Card label="Tokens entrada/salida" value={`${data.inputTokens} / ${data.outputTokens}`}/><Card label="Pruebas premium" value={data.trialUses}/></div>
 <section className="mt-7"><h2 className="text-xl font-bold">Alertas</h2><div className="mt-3 grid gap-3 md:grid-cols-3"><Link href="/admin/requests" className="rounded-xl border border-amber-200 bg-amber-50 p-4 font-semibold">{data.pendingRequests} pendientes · {data.staleRequests} fuera de plazo</Link><Link href="/admin/plans" className="rounded-xl border border-amber-200 bg-amber-50 p-4 font-semibold">{data.subscriptionAlerts} suscripciones vencidas/past due</Link><Link href="/admin/settings" className="rounded-xl border border-amber-200 bg-amber-50 p-4 font-semibold">{data.pendingDeletions} borrados pendientes</Link></div></section>
 <div className="mt-7 grid gap-4 lg:grid-cols-2"><MetricTable title="Usos por tarea" rows={data.taskUses}/><MetricTable title="Usos por plan" rows={data.planUses}/></div>
 <section className="mt-7 rounded-2xl border border-[#d9dee7] bg-white p-5"><h2 className="text-xl font-bold">Proveedor y modelo</h2><table className="mt-4 w-full text-left text-sm"><thead><tr><th>Modelo</th><th>Intentos</th><th>Fallos</th></tr></thead><tbody>{modelStats.map(([name,stat])=><tr key={name} className="border-t"><td className="py-3">{name}</td><td>{stat.total}</td><td>{stat.failed}</td></tr>)}</tbody></table></section>{data.modelAlertActive?<p className="mt-4 rounded-xl border border-red-200 bg-red-50 p-4 font-bold text-red-800">La tasa de fallos supera el umbral configurado.</p>:null}</>;
}
function MetricTable({title,rows}:{title:string;rows:[string,number][]}){return <section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">{title}</h2>{rows.map(([key,value])=><p key={key} className="mt-2 flex justify-between gap-3 text-sm"><span className="truncate">{key}</span><strong>{value}</strong></p>)}</section>}
